package services

import "errors"

var (
	ErrNameRequired       = errors.New("name is required")
	ErrLockerExists       = errors.New("locker already exists")
	ErrLockerNotFound     = errors.New("locker not found")
	ErrInvalidIP          = errors.New("IP address is not valid")
	ErrInvalidKind        = errors.New("choose pistol or rifle")
	ErrServiceNoRequired  = errors.New("service number is required")
	ErrInvalidRole        = errors.New("role must be admin or requester")
	ErrUserExists         = errors.New("a user with this service number already exists")
	ErrUserNotFound       = errors.New("user not found")
	ErrInvalidDescriptor  = errors.New("face data is not valid")
	ErrInvalidCapacity    = errors.New("capacity must be between 1 and 5")
	ErrRequestNotFound    = errors.New("request not found")
	ErrRequestClosed      = errors.New("this request was already handled")
	ErrNoneAvailable      = errors.New("none of that type is available right now")
	ErrNotAdmin           = errors.New("only an admin can do this")
	ErrRequestOpen        = errors.New("you already have a request in progress")
	ErrInvalidReturn      = errors.New("choose how long you need it")
	ErrUsernameRequired   = errors.New("username is required")
	ErrPasswordTooShort   = errors.New("password must be at least 8 characters")
	ErrInvalidLogin       = errors.New("incorrect username or password")
	ErrSetupComplete      = errors.New("admin setup is already complete")
	ErrEnrollmentPending  = errors.New("an enrollment request for this service number is already waiting")
	ErrEnrollmentNotFound = errors.New("enrollment request not found")
	ErrEnrollmentHandled  = errors.New("this enrollment request was already handled")
	ErrInvalidSlot        = errors.New("that gun number is not in this locker")
	ErrGunUnavailable     = errors.New("one of the chosen guns is no longer available")
)
